name: avzag
description: The language onslaught.
version: 0.3.12+17

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^10.0.2
  url_launcher: ^6.0.4
  expandable: ^5.0.1
  shared_preferences: ^2.0.6
  firebase_auth: ^3.0.2
  google_sign_in: ^5.0.4
  just_audio: ^0.9.5
  algolia: ^1.0.1
  flutter_markdown: ^0.6.3
  sliding_up_panel: ^2.0.0+1
  package_info_plus: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.0

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - icon.png
    - algolia.png
    - firebase.png
