name: avzag
description: Extensible parallel language compendium.
publish_to: "none"
version: 0.5.2+52

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.2
  cloud_firestore: ^3.1.1
  firebase_storage: ^10.2.0
  url_launcher: ^6.0.17
  shared_preferences: ^2.0.9
  firebase_auth: ^3.3.0
  google_sign_in: ^5.2.1
  algolia: ^1.0.3
  flutter_markdown: ^0.6.8
  package_info_plus: ^1.3.0
  provider: ^6.0.1
  flutter_speed_dial: ^4.6.6
  badges: ^2.0.2
  infinite_scroll_pagination: ^3.1.0
  flutter_map: ^0.14.0
  latlong: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
