name: bazur
description: Extensible parallel dictionary
publish_to: "none"
version: 1.1.5+75

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  url_launcher: ^6.1.4
  shared_preferences: ^2.0.15
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  crypto: ^3.0.2
  algolia: ^1.1.1
  markdown: ^7.2.1
  flutter_markdown: ^0.6.10+2
  package_info_plus: ^4.2.0
  provider: ^6.0.3
  infinite_scroll_pagination: ^4.0.0
  flutter_map: ^4.0.0
  flutter_map_marker_cluster: ^1.1.1
  latlong2: ^0.8.1
  intersperse: ^2.0.0
  google_fonts: ^4.0.4
  auto_route: ^7.8.4
  url_strategy: ^0.2.0
  modal_bottom_sheet: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  auto_route_generator: ^7.3.2

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
 
               
        